services:
  db:
    image: postgis:17-3.5
    container_name: harvest_restrictions-db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DATABASE=postgres
  app:
    build: .
    container_name: harvest_restrictions-client
    volumes:
      - "./:/home/harvest_restrictions"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - BUCKET=${BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_VIRTUAL_HOSTING=${AWS_VIRTUAL_HOSTING}
      - AWS_EC2_METADATA_DISABLED=${AWS_EC2_METADATA_DISABLED}
      - CPL_VSISTDIN_BUFFER_LIMIT=${CPL_VSISTDIN_BUFFER_LIMIT}
    depends_on:
      db:
        condition: service_healthy