name: Download
on:
  workflow_dispatch:
  workflow_call:
env:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  AWS_ENDPOINT_URL: "https://nrs.objectstore.gov.bc.ca"
  AWS_S3_ENDPOINT: "nrs.objectstore.gov.bc.ca"
  AWS_VIRTUAL_HOSTING: "FALSE"
  AWS_EC2_METADATA_DISABLED: "true"
  CPL_VSISTDIN_BUFFER_LIMIT: -1
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  download:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/harvest-restrictions:main
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Download sources to file
        run: /venv/bin/python download.py sources.json -v
  process:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/harvest-restrictions:main
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Process overlays and dump results to file
        run: process.sh