name: Harvest restrictions
on:
  workflow_dispatch:
  workflow_call:
env:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  AWS_ENDPOINT_URL: "https://nrs.objectstore.gov.bc.ca"
  AWS_S3_ENDPOINT: "nrs.objectstore.gov.bc.ca"
  AWS_VIRTUAL_HOSTING: "FALSE"
  AWS_EC2_METADATA_DISABLED: "true"
  CPL_VSISTDIN_BUFFER_LIMIT: -1
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  harvest-restrictions:
    runs-on: ubuntu-latest
    name: harvest-restrictions
    container: ghcr.io/bcgov/harvest-restrictions:main
    environment: production
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - name: Download sources
        run: |
          /venv/bin/python download.py sources.json -v
      - name: Process overlays
        run: |
          source /venv/bin/activate
          ./process.sh