name: Test
on:
  push:
    branches: [ main]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'harvest_restrictions.py'
      - 'test_harvest_restrictions.py'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'harvest_restrictions.py'
      - 'test_harvest_restrictions.py'
      - 'source.schema.json'
      - 'sources.json'
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    container: ghcr.io/bcgov/harvest-restrictions:main
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: |
          /venv/bin/python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          /venv/bin/python -m pytest -v -rxXs
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
