name: Test download script
on:
  push:
    branches: [ main]
    paths:
      - '.github/workflows/test-download.yaml'
      - 'requirements*.txt'
      - 'download.py'
      - 'test_download.py'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test-download.yaml'
      - 'requirements*.txt'
      - 'download.py'
      - 'test_download.py'
env:
  AWS_ENDPOINT_URL: "https://nrs.objectstore.gov.bc.ca"
  AWS_S3_ENDPOINT: "nrs.objectstore.gov.bc.ca"
  AWS_VIRTUAL_HOSTING: "FALSE"
  AWS_EC2_METADATA_DISABLED: "true"
  CPL_VSISTDIN_BUFFER_LIMIT: -1
  BUCKET: ${{ secrets.BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    container: ghcr.io/bcgov/harvest-restrictions:main
    environment: production
    env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          python -m pytest -v -rxXs
      - name: Validate sources.json
        run: |
          python download.py download sources.json --dry_run -v