name: Test
on:
  push:
    branches: [ main]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'harvest_restrictions.py'
      - 'test_harvest_restrictions.py'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'
      - 'requirements*.txt'
      - 'harvest_restrictions.py'
      - 'test_harvest_restrictions.py'
      - 'source.schema.json'
      - 'sources.json'
env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
  AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT  }}
  AWS_VIRTUAL_HOSTING: ${{ vars.AWS_VIRTUAL_HOSTING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_EC2_METADATA_DISABLED: ${{ vars.AWS_EC2_METADATA_DISABLED }}
  CPL_VSISTDIN_BUFFER_LIMIT: ${{ vars.CPL_VSISTDIN_BUFFER_LIMIT }}
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    container: ghcr.io/bcgov/harvest-restrictions:main
    environment: production
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: |
          /venv/bin/python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          /venv/bin/python -m pytest -v -rxXs
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
